
title: Documentation
description: >- # this means to ignore newlines until "baseurl:"
  When reviewing a PR for this repo, you can see what the documentation,
  e.g. the storybook, will look like when published for the branches
  named above.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

# Build settings
theme: minima
plugins:
  - jekyll-feed

collections:
  branches:
    output: true
    permalink: /branches/:path/

repo_name: "TBD"


repo: ucsb-cs156-s26/STARTER-team02
owner: ucsb-cs156-s26
repo_name: STARTER-team02
pull_requests: [{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-add-url-table","number":101,"title":"add urlTable component","url":"https://github.com/ucsb-cs156-s26/STARTER-team02/pull/101"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-expose-ids","number":100,"title":"pc - exclude RestConfig from pitest mutation testing","url":"https://github.com/ucsb-cs156-s26/STARTER-team02/pull/100"},{"author":{"id":"MDQ6VXNlcjExMTkwMTc=","is_bot":false,"login":"pconrad","name":"Phill Conrad"},"headRefName":"pc-url-fixtures","number":98,"title":"pc - add fixtures for urls matching format of Spring Rest API","url":"https://github.com/ucsb-cs156-s26/STARTER-team02/pull/98"}]
