name: 99 - Create Issues for team02

env:
  GH_TOKEN: ${{ github.token }}
  ASSIGNMENT: team02
  PREV_ASSIGNMENT: team01
  ASN_LINK: https://ucsb-cs156.github.io/s26/lab/team02
  STARTER_REPO: "ucsb-cs156-s26/STARTER-team02"
  FRONTEND_URL: "{ \"UCSBDiningCommonsMenuItem\": \"diningcommonsmenuitem\", \"UCSBOrganization\": \"ucsborganization\", \"RecommendationRequest\": \"recommendationrequest\", \"MenuItemReview\": \"menuitemreview\", \"HelpRequest\": \"helprequest\", \"Articles\": \"articles\" }"
  FIXTURES: "{ \"UCSBDiningCommonsMenuItem\": \"ucsbDiningCommonsMenuItem\", \"UCSBOrganization\": \"ucsbOrganization\", \"RecommendationRequest\": \"recommendationRequest\", \"MenuItemReview\": \"menuItemReview\", \"HelpRequest\": \"helpRequest\", \"Articles\": \"articles\" }"
  LABEL_COLOR: "{ \"UCSBDiningCommonsMenuItem\": \"ff0000\", \"UCSBOrganization\": \"00ff00\", \"RecommendationRequest\": \"0000ff\", \"MenuItemReview\": \"ff00ff\", \"HelpRequest\": \"ffff00\", \"Articles\": \"00ffff\" }"
  REPO_FILE: https://github.com/${{github.repository}}/blob/main
  NVM_USE: "`nvm use 22.18.0`"
  SAMPLE_TEAM: s26-05
on:
  workflow_dispatch:
    inputs:
       oneOffIssues:
         type: boolean
         default: true
         
jobs:
  createIssues:
    uses: ucsb-cs156-s26/STARTER-team02/.github/workflows/92-create-issues-for-db-table.yml@main
    with: 
      api: ${{ matrix.api }}
    strategy:
      max-parallel: 1
      matrix:
        api:
          [
            "UCSBDiningCommonsMenuItem",
            "UCSBOrganization",
            "RecommendationRequest",
            "MenuItemReview",
            "HelpRequest",
            "Articles",
          ]
          
  createOneOffIssues:
    if: ${{ inputs.oneOffIssues }}
    needs: [createIssues]
    uses: ucsb-cs156-s26/STARTER-team02/.github/workflows/91-create-one-off-issues.yml@main 
